# Generated by Django 2.2.10 on 2020-05-27 07:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psid', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('device', models.CharField(choices=[('PS4', 'PS4'), ('PC', 'PC')], default='PS4', max_length=20)),
                ('purpose', models.CharField(choices=[('カジュアル', 'カジュアル'), ('ランクマッチ', 'ランクマッチ'), ('イベント', 'イベント')], default='カジュアル', max_length=20)),
                ('rank', models.CharField(blank=True, choices=[('', '指定なし'), ('bronz', 'ブロンズ'), ('silver', 'シルバー'), ('gold', 'ゴールド'), ('platinum', 'プラチナ'), ('diamond', 'ダイヤ'), ('master', 'マスター'), ('predator', 'プレデター')], default='指定なし', max_length=20)),
                ('num', models.CharField(blank=True, choices=[('', '指定なし'), ('1', 1), ('2', 2), ('3', 3), ('4', 4)], default='指定なし', max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post')),
            ],
        ),
    ]
