# Generated by Django 2.2.10 on 2020-03-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='device',
            field=models.CharField(choices=[('ps4', 'PS4'), ('pc', 'PC')], default='ps4', max_length=200),
        ),
    ]
