# Generated by Django 2.2.10 on 2020-03-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='purpose',
            field=models.CharField(choices=[('カジュアル', 'カジュアル'), ('rank', 'ランクマッチ'), ('event', 'イベント')], default='rank', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='device',
            field=models.CharField(choices=[('ps4', 'PS4'), ('pc', 'PC')], default='ps4', max_length=20),
        ),
    ]
