# Generated by Django 2.2.10 on 2020-03-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200319_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='purpose',
            field=models.CharField(choices=[('カジュアル', 'カジュアル'), ('rank', 'ランクマッチ'), ('event', 'イベント')], default='カジュアル', max_length=20),
        ),
    ]
