# Generated by Django 2.2.10 on 2020-03-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200319_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='device',
            field=models.CharField(choices=[('PS4', 'PS4'), ('PC', 'PC')], default='ps4', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='purpose',
            field=models.CharField(choices=[('カジュアル', 'カジュアル'), ('ランクマッチ', 'ランクマッチ'), ('イベント', 'イベント')], default='カジュアル', max_length=20),
        ),
    ]
