# Generated by Django 2.2.10 on 2020-05-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200319_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='num',
            field=models.CharField(choices=[('', '---------'), (1, 1), (2, 2), (3, 3), (4, 4)], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='rank',
            field=models.CharField(choices=[('', '---------'), ('bronz', 'ブロンズ'), ('silver', 'シルバー'), ('gold', 'ゴールド'), ('platinum', 'プラチナ'), ('diamond', 'ダイヤ'), ('master', 'マスター'), ('predator', 'プレデター')], default='', max_length=20),
        ),
    ]
