# Generated by Django 2.2.10 on 2020-05-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200523_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='num',
            field=models.CharField(choices=[('', '指定なし'), ('1', 1), ('2', 2), ('3', 3), ('4', 4)], default='指定なし', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='rank',
            field=models.CharField(choices=[('', '指定なし'), ('bronz', 'ブロンズ'), ('silver', 'シルバー'), ('gold', 'ゴールド'), ('platinum', 'プラチナ'), ('diamond', 'ダイヤ'), ('master', 'マスター'), ('predator', 'プレデター')], default='指定なし', max_length=20),
        ),
    ]
